"""deals_and_finance

Revision ID: be4ef1c74335
Revises: de42c1dc74c5
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "be4ef1c74335"
down_revision: str | None = "de42c1dc74c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deals",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("partner", sa.String(length=200), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("contact_person", sa.String(length=128), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("gst_number", sa.String(length=32), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("region", sa.String(length=128), nullable=False),
        sa.Column("start", sa.Date(), nullable=False),
        sa.Column("end", sa.Date(), nullable=False),
        sa.Column("terms", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint('"end" >= start', name=op.f("ck_deals_valid_deal_dates")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deals")),
    )
    op.create_index(op.f("ix_deals_region"), "deals", ["region"], unique=False)
    op.create_table(
        "finance_entries",
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("paid", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('revenue', 'expense', 'payout')",
            name=op.f("ck_finance_entries_valid_finance_kind"),
        ),
        sa.CheckConstraint(
            "amount >= 0 AND tax >= 0", name=op.f("ck_finance_entries_nonnegative_money")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finance_entries")),
    )
    op.create_index(
        op.f("ix_finance_entries_occurred_on"), "finance_entries", ["occurred_on"], unique=False
    )
    op.create_table(
        "deal_redemptions",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_deal_redemptions_positive_quantity")),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deals.id"],
            name=op.f("fk_deal_redemptions_deal_id_deals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deal_redemptions")),
    )
    op.create_index(
        op.f("ix_deal_redemptions_deal_id"), "deal_redemptions", ["deal_id"], unique=False
    )
    op.create_index(
        op.f("ix_deal_redemptions_occurred_on"), "deal_redemptions", ["occurred_on"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deal_redemptions_occurred_on"), table_name="deal_redemptions")
    op.drop_index(op.f("ix_deal_redemptions_deal_id"), table_name="deal_redemptions")
    op.drop_table("deal_redemptions")
    op.drop_index(op.f("ix_finance_entries_occurred_on"), table_name="finance_entries")
    op.drop_table("finance_entries")
    op.drop_index(op.f("ix_deals_region"), table_name="deals")
    op.drop_table("deals")
    # ### end Alembic commands ###
