"""initial_schema

Revision ID: de42c1dc74c5
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "de42c1dc74c5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("whatsapp_user_id", sa.String(length=32), nullable=False),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_whatsapp_user_id"), "users", ["whatsapp_user_id"], unique=True)
    op.create_table(
        "webhook_events",
        sa.Column("event_key", sa.String(length=768), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("processing_error", sa.String(length=128), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_message_id", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint("event_key", name=op.f("uq_webhook_events_event_key")),
    )
    op.create_index(
        "ix_webhook_status_pending",
        "webhook_events",
        ["provider_message_id", "processed"],
        unique=False,
    )
    op.create_table(
        "conversations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "CLOSED", name="conversation_status"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_index(
        "uq_conversations_active_user",
        "conversations",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "farmer_crops",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("crop_name", sa.String(length=128), nullable=False),
        sa.Column("variety", sa.String(length=128), nullable=True),
        sa.Column("season", sa.String(length=64), nullable=True),
        sa.Column("sowing_date", sa.Date(), nullable=True),
        sa.Column("area", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("area_unit", sa.String(length=32), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "HARVESTED", "INACTIVE", name="farmer_crop_status"),
            nullable=False,
        ),
        sa.Column("source_message_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("area >= 0", name=op.f("ck_farmer_crops_nonnegative_area")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_farmer_crops_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_farmer_crops")),
        sa.UniqueConstraint("source_message_id", name=op.f("uq_farmer_crops_source_message_id")),
    )
    op.create_index(op.f("ix_farmer_crops_user_id"), "farmer_crops", ["user_id"], unique=False)
    op.create_table(
        "farmer_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("preferred_language", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=128), nullable=True),
        sa.Column("district", sa.String(length=128), nullable=True),
        sa.Column("village", sa.String(length=128), nullable=True),
        sa.Column("farm_size", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("farm_size_unit", sa.String(length=32), nullable=True),
        sa.Column("soil_type", sa.String(length=128), nullable=True),
        sa.Column("irrigation_type", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("farm_size >= 0", name=op.f("ck_farmer_profiles_nonnegative_farm_size")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_farmer_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_farmer_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_farmer_profiles_user_id")),
    )
    op.create_table(
        "messages",
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("whatsapp_message_id", sa.String(length=512), nullable=True),
        sa.Column(
            "direction", sa.Enum("INBOUND", "OUTBOUND", name="message_direction"), nullable=False
        ),
        sa.Column(
            "role", sa.Enum("USER", "ASSISTANT", "SYSTEM", name="message_role"), nullable=False
        ),
        sa.Column(
            "message_type",
            sa.Enum(
                "TEXT",
                "IMAGE",
                "AUDIO",
                "VIDEO",
                "DOCUMENT",
                "LOCATION",
                "CONTACT",
                "INTERACTIVE",
                "BUTTON",
                "REACTION",
                "UNKNOWN",
                name="message_type",
            ),
            nullable=False,
        ),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "PROCESSING",
                "GENERATED",
                "PENDING_SEND",
                "SENT",
                "DELIVERED",
                "READ",
                "FAILED",
                name="message_status",
            ),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.String(length=256), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reply_to_id", sa.Uuid(), nullable=True),
        sa.Column("send_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reply_to_id"],
            ["messages.id"],
            name=op.f("fk_messages_reply_to_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_messages_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("reply_to_id", name=op.f("uq_messages_reply_to_id")),
        sa.UniqueConstraint("sequence", name=op.f("uq_messages_sequence")),
        sa.UniqueConstraint("whatsapp_message_id", name=op.f("uq_messages_whatsapp_message_id")),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(
        "ix_messages_conversation_sequence",
        "messages",
        ["conversation_id", "sequence"],
        unique=False,
    )
    op.create_index(op.f("ix_messages_user_id"), "messages", ["user_id"], unique=False)
    op.create_foreign_key(
        "fk_farmer_crops_source_message_id_messages",
        "farmer_crops",
        "messages",
        ["source_message_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "processing_jobs",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("message_sequence", sa.BigInteger(), nullable=False),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "RETRY",
                name="processing_job_status",
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("last_error", sa.String(length=128), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND max_attempts > 0", name=op.f("ck_processing_jobs_valid_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_processing_jobs_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_processing_jobs_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
        sa.UniqueConstraint("message_id", name=op.f("uq_processing_jobs_message_id")),
    )
    op.create_index(
        "ix_jobs_conversation_order",
        "processing_jobs",
        ["conversation_id", "message_sequence"],
        unique=False,
    )
    op.create_index("ix_jobs_poll", "processing_jobs", ["status", "available_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_jobs_poll", table_name="processing_jobs")
    op.drop_index("ix_jobs_conversation_order", table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_constraint(
        "fk_farmer_crops_source_message_id_messages", "farmer_crops", type_="foreignkey"
    )
    op.drop_index(op.f("ix_messages_user_id"), table_name="messages")
    op.drop_index("ix_messages_conversation_sequence", table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_table("farmer_profiles")
    op.drop_index(op.f("ix_farmer_crops_user_id"), table_name="farmer_crops")
    op.drop_table("farmer_crops")
    op.drop_index(
        "uq_conversations_active_user",
        table_name="conversations",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_webhook_status_pending", table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_users_whatsapp_user_id"), table_name="users")
    op.drop_table("users")
    for enum in (
        "processing_job_status",
        "message_status",
        "message_type",
        "message_role",
        "message_direction",
        "farmer_crop_status",
        "conversation_status",
    ):
        sa.Enum(name=enum).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
